### ISSUE TITLE
Roadmap for new version

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPPresentation#634]
- [x] Migration to Github Actions from Travis CI
    - #635 
- [x] Support for recents versions of PHP and remove support for PHP < 7.1
    - #636
- [x] Add PHPStan
    - #639
- [x] Add PHPCSFixer
    - #637
    - #640 
- [x] Use Coveralls for replacing Scrutinizer
    - #648
- [x] Remove all deprecated
    - #650
- [x] Migration documentation to Markdown (@mkdocs)
    - #647
    - #649
- [x] Migrate from PHPExcel to PhpSpreadsheet
    - #652
- [x] Define new exceptions for each error
    - #677 
- [x] Add declare strict_types for each file
    - #673
- [x] Upgrade major version of PHPOffice\Common
    - #679
